### ISSUE TITLE
ModuleNotFoundError: No module named 'constants'

### ISSUE THREAD

**Issue by DhanjalJK** [raphael-group/weighted-exclusivity-test#24]
1. While running compute_mutation_probabilities.py I am encountering the following error:
Traceback (most recent call last):
  File "../compute_mutation_probabilities.py", line 10, in <module>
    from wext import *
  File "/root/Desktop/Jaspreet/wext-master/wext/__init__.py", line 4, in <module>
    from constants import *
ModuleNotFoundError: No module named 'constants'

Python 3.6.3 is installed on my system with CentOS. 

2. How to decide the number of permutations?

Kindly help. Thanks!

**Comment by matthewreyna** [comment]
1. This error likely occurs because of differences between Python 2 and Python 3.  We originally developed and tested WExT using Python 2.  I would recommend running WExT with Python 2 for now if possible.
2. We used 1000 permutations for the results in Sections 3.5 and 3.6 of the WExT paper, so I would consider starting with 1000 permutations.  If the permutations complete quickly, then you may want to choose a larger number of permutations. For reference, each permutation requires roughly one second, but the amount of time depends on the size (number of mutations) of your data, the speed of your machine, and the number of cores (`-nc`/`--number_cores`) allotted in the  `compute_mutation_probabilities.py` script.
